### ISSUE TITLE
Doesn't swipe forward if there's no backward available

### ISSUE THREAD

**Issue by Benedolt** [selleronom/PrecisionTouchPadSwipe#1]
Doesn't swipe forward if the "back" arrow in the UI is grayed out.

**Comment by selleronom** [comment]
Trying to replicate this but for me it is working. 
The add-on is not working on the "New Tab" page, is that what is happening for you? 

What works for me:
1. Open a bookmark
2. Click on a link
3. Swipe back
4. "Back" arrow is now greyed out
5. Swipe forward = works

**Comment by Benedolt** [comment]
Thanks for replying! It now works for me - no idea what the issue was...
