### ISSUE TITLE
Setting number of horizontal distance to trigger an event

### ISSUE THREAD

**Issue by melihozbek** [selleronom/PrecisionTouchPadSwipe#2]
Hi, first off great job with the extension! But when I use both fingers with vertical scrolling, your extension triggers back and forward events, although my intention is to simply go up and down a page. Is there a way to set a minimum distance (pixels, mm, etc) so that I can use continue to use both fingers for vertical scrolling, without interfering with your extension? Thanks,

**Comment by voidpumpkin** [comment]
up

**Comment by selleronom** [comment]
Will look into this!
